/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Account role type
 */
export const AccountRoleTypeApi = {
    RoleSession: 'ROLE_SESSION',
    RoleUser: 'ROLE_USER'
} as const;
export type AccountRoleTypeApi = typeof AccountRoleTypeApi[keyof typeof AccountRoleTypeApi];

