/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Conclusion data type
 */
export interface ConclusionApi { 
    /**
     * Conclusion reference identifier
     */
    rid?: string;
}

