/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Date data type defines a genealogical date.
 */
export interface DateApi { 
    /**
     * The original value of the date as supplied by the contributor.
     */
    original?: string;
    /**
     * The standardized formal value of the date, formatted according to the GEDCOM X Date Format specification.
     */
    formal?: string;
}

