/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateApi } from './date';


/**
 * The Fact data type defines a data item that is presumed to be true about a specific subject, such as a person or relationship.
 */
export interface FactApi { 
    /**
     * Enumerated value identifying the type of the fact.
     */
    type?: string;
    /**
     * The date of applicability of the fact.
     */
    date?: DateApi;
}

