/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Gender data type defines a gender of a person.
 */
export interface GenderApi { 
    /**
     * Conclusion reference identifier
     */
    rid?: string;
    /**
     * Enumerated value identifying the gender.
     */
    type?: string;
}

