/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NameFormApi } from './nameForm';


/**
 * A Name is intended to represent a single variant of a person\'s name.
 */
export interface NameApi { 
    /**
     * Enumerated value identifying the name type.
     */
    type?: string;
    /**
     * The name form(s) that best express this name, usually representations considered proper and well formed in the person\'s native, historical cultural context.
     */
    nameForms?: Array<NameFormApi>;
}

