/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * NamePart data type is used to model a portion of a full name.
 */
export interface NamePartApi { 
    /**
     * Enumerated value identifying the type of the name part.
     */
    type?: string;
    /**
     * The term(s) from the name that make up this name part.
     */
    value?: string;
}

