/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Known Name Part Types
 */
export const NamePartTypeApi = {
    HttpGnaBzblzPrefix: 'http://gna.bzblz/Prefix',
    HttpGnaBzblzSuffix: 'http://gna.bzblz/Suffix',
    HttpGnaBzblzGiven: 'http://gna.bzblz/Given',
    HttpGnaBzblzSurname: 'http://gna.bzblz/Surname'
} as const;
export type NamePartTypeApi = typeof NamePartTypeApi[keyof typeof NamePartTypeApi];

