/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamePartApi } from './namePart';


/**
 * The NameForm data type defines a representation of a name.
 */
export interface NameFormApi { 
    /**
     * A full rendering of the name (or as much of the name as is known).
     */
    fullText?: string;
    /**
     * Any identified name parts from the name.
     */
    parts?: Array<NamePartApi>;
}

