/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NameApi } from './name';
import { GenderApi } from './gender';


/**
 * The Person data type defines a description of a person.
 */
export interface PersonApi { 
    /**
     * Conclusion reference identifier
     */
    rid?: string;
    /**
     * Person UUID
     */
    id?: string;
    /**
     * Project UUID
     */
    projectId?: string;
    /**
     * Project data version.
     */
    version?: number;
    /**
     * Project creation date.
     */
    createdAt?: string;
    /**
     * The sex of the person as assigned at birth.
     */
    gender?: GenderApi;
    /**
     * The names of the person.
     */
    names?: Array<NameApi>;
}

