/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The Project data type.
 */
export interface ProjectApi { 
    /**
     * Project UUID.
     */
    id?: string;
    /**
     * Project data version.
     */
    version?: number;
    /**
     * Project creation date.
     */
    createdAt?: string;
    /**
     * Project owner account UUID.
     */
    accountId?: string;
    /**
     * Project title
     */
    title: string;
}

