/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NamePartTypeApi } from './namePartType';
import { UriDtoApi } from './uriDto';


/**
 * Defined enums, types
 */
export interface SchemasApi { 
    /**
     * Gender Type Uri Dictionary
     */
    baseGenderTypeUri?: Array<UriDtoApi>;
    /**
     * Name Type Uri Dictionary
     */
    baseNameTypeUri?: Array<UriDtoApi>;
    /**
     * Name Part Type Uri Dictionary
     */
    baseNamePartTypeUri?: Array<UriDtoApi>;
    /**
     * Name Part Type Uri Enum
     */
    baseNamePartTypeUriEnum?: NamePartTypeApi;
}
export namespace SchemasApi {
}


